name: robodiff312
channels:
  - pytorch
  - pytorch3d
  - nvidia
  - conda-forge
dependencies:
  - python=3.12
  - pip=24.2
  - setuptools<81
  - pytorch-cuda=12.1
  - pytorch=2.4.1
  - torchvision=0.19.1
  - pytorch3d=0.7.8
  - numpy=1.26.4
  - numba=0.60.0
  - scipy=1.14.1
  - py-opencv=4.10.0
  - cffi=1.17.1
  - ipykernel=6.29.5
  - matplotlib=3.9.2
  - zarr=2.18.3
  - numcodecs=0.13.0
  - h5py=3.11.0
  - hydra-core=1.3.2
  - einops=0.8.0
  - tqdm=4.66.5
  - dill=0.3.8
  - scikit-video=1.1.11
  - scikit-image=0.24.0
 # - gym=0.26.2
  - pymunk=6.8.1
  - wandb
  - threadpoolctl=3.5.0
  - shapely=2.0.6
  - cython=3.0.11
  - imageio=2.35.1
  - imageio-ffmpeg=0.5.1
  - termcolor=2.4.0
  - tensorboard=2.17.1
  - tensorboardx=2.6.2.2
  - psutil=6.0.0
  - click=8.1.7
  - boto3=1.35.24
  - accelerate=0.34.2
  - datasets=3.0.0
  - diffusers=0.30.3
  - av=13.0.0
  - cmake=3.30.3
  # trick to avoid cpu affinity issue described in https://github.com/pytorch/pytorch/issues/99625
  - llvm-openmp=18
  # trick to force reinstall imagecodecs via pip
  - imagecodecs==2024.6.1
  - pip:
    - ray[default,tune]==2.35.0
    # requires mujoco py dependencies libosmesa6-dev libgl1-mesa-glx libglfw3 patchelf
    # - free-mujoco-py==2.1.6
    - pygame==2.6.0
    - pybullet-svl==3.1.6.4
    # - robosuite @ https://github.com/cheng-chi/robosuite/archive/277ab9588ad7a4f4b55cf75508b44aa67ec171f0.tar.gz
    - robomimic==0.2.0
    - pytorchvideo==0.1.5
    # pip package required for jpeg-xl
    - imagecodecs==2024.6.1
    - r3m @ https://github.com/facebookresearch/r3m/archive/b2334e726887fa0206962d7984c69c5fb09cceab.tar.gz
    # - dm-control==1.0.9
